### ISSUE TITLE
Bootstrap to setup a home page with a list of posts - as per WP default

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#102]
#### Expected behaviour
Home page to show all recent posts

#### Actual behaviour
Missing component

**Comment by thomasdigby** [comment]
For reference [improve-bootstrap-output](https://github.com/shortlist-digital/tapestry-wp/tree/improve-bootstrap-output)

**Comment by thomasdigby** [comment]
Implemented in #163
