### ISSUE TITLE
Fix data normalisation from API

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#127]
Let's defo `toArray` that nasty `{ 0: {}, 1: {} }`, but otherwise we should probably leave the data schema as is.

```
let data = ('0' in resp) || resp instanceof Array ? {
  posts: toArray(resp)
} : resp
if (data.posts && data.posts.length == 1)  {
  data = data.posts[0]
}
```

**Comment by jonsherrard** [comment]
50p to anyone who can describe why it's ending up as`{ 0: {}, 1: {} }` in the first place.
