### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by maciekpaprocki** [shortlist-digital/tapestry-wp#171]
Now, when we have tapestry plugin we can add previews:

To get preview use `revision/v1` in your endpoint instead of `wp/v2` and pass wp_tapestry arguments passed from dashboard preview link. 

ex.
`/wp-json/wp/v2/posts/117260`
becomes
`/wp-json/revision/v1/posts/117262?tapestry_hash=96f6c4c1ef7bf947df892509bba96ddbca92e394&p=117262`

This will let you download item review without full wordpress authentication. 

If you will have any issues with returned json give me a shout and I will see how to update that.

**Comment by thomasdigby** [comment]
Implemented in #179
