### ISSUE TITLE
Initial Documentation

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#18]
Topics to cover:

 - Why
 - setup
   - .gitignore // .tapestry
   - add scripts
   - demo API // Can we build a static demo API on S3?
 - `tapestry.config.js`
 - `dev`, `build` and `start` commands
 - Wordpress API & Tapestry API
 - Routing
 - React
 - Glamor CSS
 - WordPress hosting // Where to get a Wordpress hosted instance with the API

**Comment by jonsherrard** [comment]
I might have a documentation day today, I've got a few other things to write as well. Any thoughts on the proposal in the first comment?
@ecoad @thomasdigby @iamdeaneyelid @mathewhawley

**Comment by thomasdigby** [comment]
Nope, it looks good.

- Why do I need this?
- What is it?
- How can I use it?
- Details

**Comment by mathewhawley** [comment]
Looks nice to me

**Comment by thomasdigby** [comment]
@jonsherrard Did you kick this off?

**Comment by jonsherrard** [comment]
Big time.
