### ISSUE TITLE
Promise is undefined

### ISSUE THREAD

**Issue by mathewhawley** [shortlist-digital/tapestry-wp#183]
#### Expected behaviour
`Promise` should be defined

#### Actual behaviour
Getting `Promise is undefined`

#### Steps to reproduce
Run the site in IE10 on Windows

#### Environment
Windows, IE10

…

**Comment by thomasdigby** [comment]
@mathewhawley Are you still getting this issue? I'm guessing not?

**Comment by mathewhawley** [comment]
@thomasdigby na haven't seen it anywhere – I guess we're all good! 👍
