### ISSUE TITLE
CLI: Build client.js only command.

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#19]
In some deployment scenarios, a user might want a command to output just the client-side `bundle.js`. E.g pushing that bundle to S3, and having it served from there.

It also follows that the `tapestry.js` config should have a method for passing in script locations...

This could either be:

 - A URL `clientUrl: 'http://cdn.site.com/commitHash/bundle.js'
 - An array of scripts to load
 - Documentation about using the `Base` component as the place to load scripts

**Comment by thomasdigby** [comment]
We could document a method of including scripts through Helmet and defining the `defer` or `async`  attributes. This would simplify the Tapestry API and allow for the best practice technique for loading scripts, reference in the `<head>` to kick off download asap, use `defer` to _defer_ parsing(?) and execution until DOMContentLoaded.

**Comment by thomasdigby** [comment]
But of course, we're still calling the `bundle.js` from within the `<DefaultHtml />`. We _could_ utilise a `publicPath` option and pass that to the HTML if used?

```js
export default {
  publicPath: 'http://cdnlocation.com',
  siteUrl: 'http://apilocation.com'
}
```

```html
<script defer src={`${config.publicPath}/_scripts/bundle.js`} />
```

**Comment by thomasdigby** [comment]
Will exposing a `publicPath` and updating the script path do the job for this issue?

Also I wonder if there will be a need for a client only build? The server and client bundles will need to be in sync so updating one and not the other will produce a `checksum` error. Are we considering supporting client only applications?

**Comment by jonsherrard** [comment]
I think the use case would be something along these lines:
```
# Deploy.sh

tapestry build:client --output-file=/tmp/something.bundle.js
aws s3 cp /tmp/something.bundle.js static.mryde.com/assets/something.bundle.js
tapestry build:server --client-location=static.mryde.com/assets/something.bundle.js
// Other stuff
```

**Comment by jonsherrard** [comment]
Discussed in IRL: We're just going to use webpack's underling `publicPath` API and refer to that in advanced documentation.
