### ISSUE TITLE
Ability to proxy URLs with regex/wildcards

### ISSUE THREAD

**Issue by ecoad** [shortlist-digital/tapestry-wp#194]
#### Expected behaviour
Our dynamic sitemap.xml results in sub sitemaps such as:
`/sitemap-pt-post-2017-06.xml`
We'd like to add `/sitemap-*` as a route to proxy.

#### Actual behaviour
Unsupported

This is a blocker for the project we're currently working on. According to @thomasdigby Hapi doesn't support regex/wildcard routes.

**Comment by jonsherrard** [comment]
Have you tried `/sitemap-*.xml` as a `proxyPath`.

Hapi docs aren't the clearest here: https://hapijs.com/tutorials/routing, but they do imply optional/wildcard routing is possible.

**Comment by jonsherrard** [comment]
More research done: Hapijs will not allow regex URLs for performance issues, preferring, you guessed - strongly unambiguous routes!

XML Sitemap Generator for WordPress, will allow you to serve the sitemaps from a `/sitemap` route, with a small change to nginx or apache.

Google allows for sitemaps to not be on the root domain: https://webmasters.googleblog.com/2007/10/dealing-with-sitemap-cross-submissions.html

**Comment by jonsherrard** [comment]
I'm going to close this as a won't fix, we should encourage unambiguous "predictive" routing.

It's never going into Hapijs https://github.com/hapijs/hapi/issues/1765#issuecomment-120104927 so we'd need to migrate to Express to get regex-able routes. @ecoad @thomasdigby
