### ISSUE TITLE
Sometimes the 404 page doesn't return Status Code 404

### ISSUE THREAD

**Issue by ecoad** [shortlist-digital/tapestry-wp#195]
#### Expected behaviour
Example URL:
http://example.com/asdfsdf/asdfsadf
Returns `200`

http://example.com/asdfsdf/asdfsadf/234
Returns `404`

#### Actual behaviour
http://example.com/asdfsdf/asdfsadf
Should return `404`

**Comment by jonsherrard** [comment]
(@ecoad scrubbed urls from public repo)

**Comment by thomasdigby** [comment]
I'll write tests for this today.
