### ISSUE TITLE
Figure out NODE_ENV

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#204]
#### Expected behaviour
No caching if the `NODE_ENV` variable *isn't* `production`

#### Actual behaviour
Tapestry caches for 2 minutes

#### Steps to reproduce
`npm run start:prod`

I think this is something to with the WebPack bundle step injecting process.env.NODE_ENV maybe....

**Comment by thomasdigby** [comment]
Let's remove that `NODE_ENV` from our webpack `DefinePlugin`, of course it should be an environment specific property.

**Comment by jonsherrard** [comment]
Closed by https://github.com/shortlist-digital/tapestry-wp/pull/268
