### ISSUE TITLE
Cache isn't cleared correctly

### ISSUE THREAD

**Issue by ecoad** [shortlist-digital/tapestry-wp#206]
I'd noticed that the cache was not purging correctly. 

This is the URL I'm hitting: **private-domain**/news/elliot/27

Response from the logs:
```
> Server returned a fresh API response over HTTP for   **private-domain**/wp-json/wp/v2/posts/27?_embed
> Server loading HTML from cache for /news/elliot/27
```
First potential issue - why is a fresh API response coming back but a cached HTML hit?

Then I "do a purge"
**private-domain**/purge/news/elliot/27

In the logs I see this:

Response from the logs:
```
> Purge request for endpoint posts/27?_embed
> Request: news/elliot/27 mapped to API: posts/27?_embed
> Directly clearing html cache for news/elliot/27
> purging news/elliot/27 from cache: html
> Clear status for `news/elliot/27`: not found
```
@jonsherrard pointed out the "the preceding slash isn’t getting passed into the clear cache bit".

Sounds like the issue.

**Comment by thomasdigby** [comment]
Fixed by #208
