### ISSUE TITLE
Add configuration to force redirecting to HTTPS

### ISSUE THREAD

**Issue by ecoad** [shortlist-digital/tapestry-wp#210]
We need the option to be able to force HTTP requests to redirect to HTTPS.

Example: http://example.com/foo/bar redirects to https://example.com/foo/bar

This I'm imagining would be a boolean configuration you could toggle.

**Comment by jonsherrard** [comment]
```
// tapestry.config.js
{
  options: {
    forceHttps: true
  }
```
