### ISSUE TITLE
jsURI

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#213]
Could we utilise https://github.com/derek-watson/jsUri to handle our URIs better throughout the codebase? There's a lot of string manipulation going on, we _should_ do this better.

**Comment by jonsherrard** [comment]
Yes I like it. Off the top of your head would this get bundled into the client code too?

**Comment by thomasdigby** [comment]
I think so as we'd need it in `fetch-route-data` among other shared JS. I'd prefer to handle our URLs without any string manipulation so whether it's this package or something else (need to check the gzip size) doesn't concern me.

**Comment by jonsherrard** [comment]
https://unpkg.com/jsuri@1.3.1 3.4kb Gzipped. But that'd drop when we bundle and minify in production. 👍

**Comment by thomasdigby** [comment]
Only found one or two places to utilise this lib, not sure we gain much from it, closing for now.
