### ISSUE TITLE
Implement HTTP Strict Transport Security if https protocol is set

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#219]
We need to add some configuration around protocols and forcing HTTPS anyway, so we should enable the browser-side upgrade HTTP STS functionality when we know Tapestry is running over HTTPS

https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Strict_Transport_Security

This will probably need to be on a configuration basis now I think about it, as I believe it upgrades all subsequent requests to HTTPS, and there maybe some third party resources on a page that a user cannot serve over HTTPS

**Comment by thomasdigby** [comment]
Should we apply this when `options: { forceHttps: true }` in `tapestry.config`?

**Comment by thomasdigby** [comment]
@jonsherrard What do you want to do about this option?

**Comment by jonsherrard** [comment]
Sit on it for a bit CSP is pretty advanced. You can inadvertently block scripts from off the top of my head:

 - segment serves their analytics snippet from cloudfront instead of segment.com?
 - alternate image domains for CDNs (in embeds)
 - your embed whitelist of trusted domains is going to be really long.
