### ISSUE TITLE
Switch Glamor SSR to renderStaticOptimized

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#22]
Glamor can inspect the HTML about to be delivered to the client and only include the CSS for that HTML. https://github.com/threepointone/glamor/blob/master/docs/server.md

**Comment by jonsherrard** [comment]
Fixed by https://github.com/shortlist-digital/tapestry-wp/pull/28

**Comment by thomasdigby** [comment]
As per my comment in #28
