### ISSUE TITLE
Replace React with Preact for production build

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#23]
It provides an identical API and can save a whole bunch of kb for the production build. Will need to test compatibility with some packages (Glamor, Helmet, Router, Object inspector) https://github.com/developit/preact-compat

**Comment by thomasdigby** [comment]
Alright, I think this will be more involved than I initially thought. We also need to cover the `renderToString` and `renderToStaticMarkup` methods which `preact-compat` doesn't cover. If we can alias `react` for client only, it might work, although then we could run into the server-checksum issue.

**Comment by jonsherrard** [comment]
If we could configure the client to use preact/inferno/new-react-compatible framework. Then yay, for now let's stick with Facebook's implementation.

**Comment by jonsherrard** [comment]
Good thread to read: https://mobile.twitter.com/dan_abramov/status/822404188055420928

**Comment by thomasdigby** [comment]
I'm going to close this, I don't think it's reasonable to switch out the entire framework just for production. However I still think it'll be useful enough on a per-project basis (Croché?) so I'll add it to that backlog instead of this.

**Comment by thomasdigby** [comment]
Just for reference when we look into this again:
```
resolve: {
  alias: {
    'react': 'preact-compat/dist/preact-compat',
    'react-dom': 'preact-compat/dist/preact-compat'
  }
}
```
