### ISSUE TITLE
Configure HAPI router to ignore case

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#232]
#### Expected behaviour
`get: /thing` == `get: /thiNG //200`

#### Actual behaviour
`get: /thing // 200`
`get: /thiNG //404`

WordPress always generate lower case slugs. I'd argue that expected functionality would be to ignore the case and match the route.

**Comment by thomasdigby** [comment]
React Router and the WordPress API are both case insensitive, where do you see the 404? Better to drop everything to lowercase anyway so opened #235
