### ISSUE TITLE
Should we handle requests to `/wp/wp-admin/index.php?page=zoneboard`?

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#234]
We _could_ leave it to the `redirectPaths` or `proxyPaths` in the `tapestry.config.js`, but it might be quite a nice default option.

**Comment by jonsherrard** [comment]
You should only be receiving requests to that endpoint if you've recently done a domain switch.

Reasons for that request being made:

 - Cached DNS
 - CMS users who have their browser still open.
