### ISSUE TITLE
Create tapestry.log file

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#240]
I've fixed the previous issue with the log file that broke the build, but I have a few questions before we add this in.

In terms of formatting for the log file, we're using `chalk` to render colors in the CLI 👌  but it outputs a unicode (?) character or 2 to the `tapestry.log`. I don't if there is a way around this as we're doing it at the log level. e.g. `log.debug('API response via cache for ${chalk.green(cacheKey)}')`

```
{"level":"debug","message":"  Using custom .babelrc from \u001b[32m/private/var/www/project-lennon/.babelrc\u001b[39m","timestamp":"2:42:26 PM"}
{"level":"debug","message":"  Server started at \u001b[32mhttp://0.0.0.0:3030\u001b[39m","timestamp":"2:42:57 PM"}
```

Do we want to create multiple log files? I assume we won't want to put it all into one _giant_ `tapestry.log`. Also, where should we store these logs? Currently it's output to the `.tapestry/` directory but will it be retained if Heroku restarts? I'm pretty sure it'll nuke the whole directory.

**Comment by mathewhawley** [comment]
https://github.com/chalk/strip-ansi might help if we want to create readable saved logs?

**Comment by mathewhawley** [comment]
Can't say much about saving/efficiency etc – not sure what the implications are ...

**Comment by thomasdigby** [comment]
@ecoad @jonsherrard Do you have any thoughts on how/where we should store this log file?

**Comment by thomasdigby** [comment]
Also, after reading through the docs, Winston exposes a `stripColors` function that removes the ANSI stuff but you can't apply it to a specific transport, e.g. `File` over `Console`. We'll have to remove the colour from both the terminal and strip the encoding issue from the log file.

I created a `env` specific function in production that strips the colors and outputs the file. #243
