### ISSUE TITLE
Replace 'fetch' API with isomorphic request solution that uses XHR for progress UI

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#26]
When the Tapestry client JS bundle picks up routing and navigation, we lose any visual feedback on the progress of a page load.

The current implementation of Fetch does not have progress events, the idea is that on-the-fly calculation will be done using streams in the future.

In the meantime we will have to use an XHR solution that an `onprogress` even on the client.

https://github.com/matthewwithanm/httpplease.js Seems like reasonable candidate - IE9 compatibility etc, haven't vetted it heavily though.

**Comment by jonsherrard** [comment]
This may be a 🌶

**Comment by thomasdigby** [comment]
[axios](https://github.com/mzabriskie/axios) looks a good bet, `onDownloadProgress` will return us a progress event. Here's an [example](https://github.com/mzabriskie/axios/issues/629#issuecomment-282986545).

How would we expose this progress event to the user? via the config? I'm struggling to understand how we'd render and update a component alongside the static main view. Whaddaya thoughts?

**Comment by jonsherrard** [comment]
```
   render(
      <div>
          <DefaultProgress value={onDownloadProgress} /> || <loadContext.customProgress value={onDownlooadProgress/ >
          <Router />
      </div>
   )
```

**Comment by thomasdigby** [comment]
https://github.com/mjackson/react-broadcast
