### ISSUE TITLE
Bootstrap simple project structure

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-wp#29]
Something similar to the `backpack init` command would be great. It would be very prescriptive but internally we'll likely stick to a consistent structure per project anyway, setting up a `package.json`, `tapestry.config.js` and some _basic_ components could be a quick win.

https://github.com/palmerhq/backpack/pull/34/files#diff-fc31ff1cef48bee524443ab53ef7da23

**Comment by jonsherrard** [comment]
```
 - package.json
 - tapestry.config.js
 - components
   - post
     - index.js
   - page
     - index.js
   - category
     - index.js
 - public
```

?

**Comment by thomasdigby** [comment]
I guess the main contention will be with the component structure, we'd _probably_ host them another level down in `/views` as it's likely we'd add some sibling directories for `partials`, `widgets` etc. when building the project.

**Comment by jonsherrard** [comment]
I agree, it's pretty easy to `mv ./components ./components/views` in our projects, for the general population maybe something like this is enough?

```
 - package.json
 - tapestry.config.js
 - components
   - Post.js
   - Page.js
   - Archive.js
 - public
```

**Comment by thomasdigby** [comment]
I think that is a _great_ solution.

**Comment by thomasdigby** [comment]
We could probably remove the `public` folder as it automatically gets wiped with each rebuild, although I guess that raises the question about hosting static assets. Especially as they'll be handled separately to the `bundle.js`

**Comment by jonsherrard** [comment]
Yeah `/public` is an issue, where does `.favicon` go etc. Do we need to wipe the bundle, or could we remove by a glob `(tapestsry-bundle.[hash].js)`

**Comment by thomasdigby** [comment]
We should probably remove it by a _glob_

**Comment by mathewhawley** [comment]
`_scripts/bundle.[chunkhash].js`

**Comment by thomasdigby** [comment]
```js
import React, { PropTypes } from 'react'

const Page = props =>
  <section>
    <h1>
      {props.title.rendered}
    </h1>
  </section>

Page.propTypes = {
  title: PropTypes.shape({
    rendered: PropTypes.string.isRequired
  }).isRequired
}

export default Page
```

Too much/little/just-right for home/page/post/archive etc. ?

**Comment by jonsherrard** [comment]
I'd vote just right - that's nice. Now I've said that would it be nice to put the JSON preview component from MissingView in there with all the props too? I feel like if I was booting it up straight from init, I'd like that information too.

**Comment by thomasdigby** [comment]
#51
