### ISSUE TITLE
Upgrade to React-Router 4

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#55]
https://reacttraining.com/react-router/

The new React Router, has a lot of nice new APIs that'll be useful for various things:

 - Testing
 - Preview.js script
 - Doing sub-routing in user-land
 - Potential React Native implementation

No rush on this I don't think though.

**Comment by thomasdigby** [comment]
I _think_ we're not upgrading due to incompatibility with AsyncProps, @jonsherrard can you confirm? Let's close this if so
