### ISSUE TITLE
Break Git and NPM History for the good of Semver

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#61]
We have broken the public API a lot in the last few versions. 

Should we roll back to a RC 0. something? OR Go to scrub everything from the internet and go to version 1.0.0, can we even delete version from NPM? 

</thought>

**Comment by thomasdigby** [comment]
I had this thought yesterday, rolling back to a 0. version could work as we implement the 1.0 feature set. We could RC or Beta the 1.0 when ready for bug-fixing.

**Comment by thomasdigby** [comment]
I still think rolling back to a `0.16.0` will be represent the package at the moment than `1.6.0` @jonsherrard
