### ISSUE TITLE
fresh init breaks on npm run bootstrap

### ISSUE THREAD

**Issue by pdme** [shortlist-digital/tapestry-wp#76]
After the following steps:

- mkdir tapestry && cd tapestry
- npm init
- npm i --save tapestry-wp
- npm run bootstrap

I get this error:

> internal/child_process.js:313
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn EACCES
>     at exports._errnoException (util.js:1026:11)
>     at ChildProcess.spawn (internal/child_process.js:313:11)
>     at exports.spawn (child_process.js:380:9)
>     at Command.executeSubCommand (/Users/pdme/Projects/tapestry/node_modules/commander/index.js:534:14)
>     at Command.parse (/Users/pdme/Projects/tapestry/node_modules/commander/index.js:463:17)
>     at Object.<anonymous> (/Users/pdme/Projects/tapestry/node_modules/tapestry-wp/bin/tapestry:17:9)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)

Am I missing something?

**Comment by jonsherrard** [comment]
Ah execution permissions haven't been committed on the bootstrap command. Will modify and get a fix out for this now. You can `chmod +x ./node_modiules/tapestry-wp/bin/tapestry-init` as a hack

**Comment by pdme** [comment]
cool, thanks!

just for future reference, there's a typo in the command above (node_modules)

**Comment by jonsherrard** [comment]
Thanks! Amended.

**Comment by jonsherrard** [comment]
Fixed in `v1.5.4`
